name: Swift (iOS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 16.4
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Build (iOS 15 simulator)
        run: swift build --triple arm64-apple-ios15.0-simulator -v

      - name: Build (iOS Simulator)
        run: swift build --destination ios15-sim.json -v
