name: Swift (iOS Build)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Create iOS 15 destination
        run: |
          SDK=$(xcrun --sdk iphoneos --show-sdk-path)
          TOOLBIN="/Applications/Xcode_16.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin"
          cat > ios15.json <<JSON
          {
            "version": 1,
            "target": "arm64-apple-ios15.0",
            "sdk": "${SDK}",
            "toolchainBinDir": "${TOOLBIN}"
          }
          JSON

      - name: Build (iOS)
        run: swift build --destination ios15.json -v
