name: Swift (iOS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 16.4
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: List schemes
        run: xcodebuild -list

      - name: Build and Test (iOS Simulator)
        run: |
          xcodebuild \
            -scheme CoreSession \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.5' \
            -configuration Debug \
            -skipPackagePluginValidation \
            -skipMacroValidation \
            test
