name: Swift (iOS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 16.4
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: List schemes
        run: xcodebuild -list -json

      - name: Build for iOS Simulator
        run: |
          xcodebuild \
            -scheme CoreSession-Package \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            -configuration Debug \
            -skipPackagePluginValidation \
            -skipMacroValidation \
            build
